version: '3'

networks:
  micultura-network:
    driver: bridge

services:
  micultura-frontend:
    container_name: micultura-frontend_container
    image: micultura-frontend:latest
    build: ./frontend/web-app/
    ports:
      - 4200:4200
    depends_on:
      - micultura-app
    networks:
      - micultura-network
      
  micultura-app:
    image: micultura-app:latest
    build: ./mi-cultura-docker/Dockerfile
    container_name: micultura_container
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mi_cultura
      - DATABASE_USER=mi_cultura
      - DATABASE_PASSWORD=micultura123
      - SPRING_PROFILE=dev
    volumes:
      - ./src/main/resources:/app/config
    depends_on:
      - mysql-db
    networks:
      - micultura-network
      
  mysql-db:
    image: mysql:8.0.27
    container_name: mysql_container
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_USER=mi_cultura
    - MYSQL_DATABASE=mi_cultura
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_PASSWORD=micultura123
    - TZ=America/Argentina/Buenos_Aires
    networks:
      - micultura-network