version: '3'
 
networks:
  mi_red:
    driver: bridge

services:
  micultura-frontend:
    container_name: micultura-frontend_container
    image: micultura-frontend:latest
    build: ./frontend/web-app/
    ports:
      - 4200:4200
    depends_on:
      - micultura-app
    networks:
      - mi_red
  micultura-app:
    image: micultura-app:latest
    container_name: micultura_container
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mi_cultura
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - SPRING_PROFILE=dev
    volumes:
      - ./src/main/resources:/app/config
    depends_on:
      - db
    networks:
      - mi_red
  db:
    image: mysql:5.7.20
    container_name: mysql_container
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_USER=root
    - MYSQL_DATABASE=micultura
    - MYSQL_ROOT_PASSWORD=admin
    - TZ=America/Argentina/Buenos_Aires
    networks:
      - mi_red