version: '3'
 
services:
  micultura-frontend:
    container_name: micultura-frontend_container
    image: micultura-frontend:latest
    build: ./frontend/web-app/
    ports:
      - 4200:4200
    depends_on:
      - micultura-app
  micultura-app:
    image: micultura-app:latest
    container_name: micultura_container
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=mi_cultura
      - DATABASE_USER=mi_cultura
      - DATABASE_PASSWORD=micultura123
    volumes:
      - ./src/main/resources:/app/config
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.7
    container_name: mariadb_container
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=mariadb123
    - TZ=America/Argentina/Buenos_Aires
    volumes:
    - ./mi-cultura-docker/mariadb/data/my.cnf:/etc/mysql/my.cnf
    - ./mi-cultura-docker/mariadb/data/config:/var/lib/mysql
    - /mi-cultura-docker/mariadb/scripts.sql:/docker-entrypoint-initdb.d