version: v1.0
services:
  my-app:
    image: charliezolezzi/micultura-app:latest
    env:
      SPRING_PROFILE: prod
    ports:
      - 8080:8080
    buildScript: ./gradlew build
    runScript: java -cp .:lib/* $JAVA_OPTS unq.edu.li.pdes.micultura.MiCulturaApplication --spring.profiles.active=${SPRING_PROFILE:-prod}