server:
  address: 0.0.0.0
  port: ${PORT:8080}
  servlet:
    contextPath: /

mysql:
  service:
    # The host of the MySQL database server, can be customized using
    # the 'MYSQL_SERVICE_HOST' env variable
    host:     localhost
    # The port of the MySQL database server, can be customized using
    # the 'MYSQL_SERVICE_PORT' env variable
    port:     3306
    # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE'
    # env variable
    database: mi_cultura 

spring:
  application:
  name: "MiCultura"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/app/frontend/web-app/dist/
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
  datasource:
    url:      jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    jdbcUrl:  jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    minimumIdle: 5
    maximumPoolSize: 5
    maxActive: 5
    maxIdle: 5
    maxWait: 1000
    validationQuery: "select 1"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
  jpa:
#    database: mysql
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.enable_lazy_load_no_trans: true

jwt:
  secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  validaty: 18000