/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AccountReviewDetailsDTO {
    accountId?: number;
    comments?: string;
    dni?: string;
    eventId?: number;
    eventType?: string;
    eventTypeDescription?: string;
    firstname?: string;
    lastname?: string;
    placeId?: number;
    placeName?: string;
    placeType?: string;
    placeTypeDescription?: string;
    reviewId?: number;
    score?: number;
    title?: string;
}
