/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorityDTO } from './authorityDTO';


export interface PlaceDTO {
    placeId?: number;
    address?: string;
    authority?: AuthorityDTO;
    dependsOn?: string;
    description?: string;
    email?: string;
    id?: number;
    isFavorite?: boolean;
    link?: string;
    name?: string;
    phoneNumber?: string;
    placeType?: string;
    placeTypeDescription?: string;
    province?: string;
    url?: string;
}
