/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlaceVO {
    placeId?: number;
    address?: string;
    authorityEmail?: string;
    authorityName?: string;
    authorityPosition?: string;
    dependsOn?: string;
    description?: string;
    email?: string;
    link?: string;
    name?: string;
    phoneNumber?: string;
    placeType?: string;
    placeTypeDescription?: string;
    province?: string;
    url?: string;
}
