name: Deploy to Railway

on:
  push:
    branches: [development_deploy]
  workflow_run:
    workflows: ["Micultura_Backend_CI", "Micultura_Frontend_CI"]
    types:
      - completed

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Initial setup
        run: echo "Initial setup - No dependencies"

  build:
    needs: [Micultura_Backend_CI, Micultura_Frontend_CI]
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build docker -Penv=dev
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag micultura-app:latest charliezolezzi/micultura-app:latest
          docker push charliezolezzi/micultura-app:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | bash
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Deploy to Railway
        if: ${{ github.event_name == 'push' }}
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link $RAILWAY_PROJECT_ID
          railway up --image charliezolezzi/micultura-app:latest
