name: Micultura
on:
  push:
    branches:
      - main 
      - development
  pull_request:
    branches:
      - main 
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Jacoco directory
      run: mkdir -p target/site/jacoco/
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: |
          ./gradlew test jacocoTestReport --no-daemon
          ./gradlew jacocoBadge
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Jacoco badge artifact
      uses: actions/upload-artifact@v2
      with:
          name: jacoco-badge
          path: build/reports/jacoco/jacocoBadge.svg
