name: Micultura
on:
  push:
    branches:
      - main 
      - development
  pull_request:
    branches:
      - main 
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport --no-daemon
