name: Micultura
on:
  push:
    branches:
      - main 
      - development
  pull_request:
    branches:
      - main 
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport --no-daemon
    - name: Upload JaCoCo reports
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-reports
        path: build/reports/jacoco/
    - name: Get coverage percentage from JaCoCo report
        id: get-coverage
        run: |
          coverage=$(awk -F ',' '{ print int($4) }' build/reports/jacoco/test/jacocoTestReport.csv)
          echo "::set-output name=coverage::$coverage"

    - name: Update README.md with coverage badge
      run: |
          coverage=$INPUT_COVERAGE
          badge_url="https://img.shields.io/badge/Coverage-${coverage}%25-brightgreen.svg"
          sed -i "s|!\[Coverage\].*|![Coverage]($badge_url)|" README.md
      env:
          NPUT_COVERAGE: ${{ steps.get-coverage.outputs.coverage }}
